Document: cdos-upgrade
Title: Debian cdos-upgrade Manual
Author: <insert document author here>
Abstract: This manual describes what cdos-upgrade is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cdos-upgrade/cdos-upgrade.sgml.gz

Format: postscript
Files: /usr/share/doc/cdos-upgrade/cdos-upgrade.ps.gz

Format: text
Files: /usr/share/doc/cdos-upgrade/cdos-upgrade.text.gz

Format: HTML
Index: /usr/share/doc/cdos-upgrade/html/index.html
Files: /usr/share/doc/cdos-upgrade/html/*.html
