Document: cos-upgrade
Title: Debian cos-upgrade Manual
Author: <insert document author here>
Abstract: This manual describes what cos-upgrade is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cos-upgrade/cos-upgrade.sgml.gz

Format: postscript
Files: /usr/share/doc/cos-upgrade/cos-upgrade.ps.gz

Format: text
Files: /usr/share/doc/cos-upgrade/cos-upgrade.text.gz

Format: HTML
Index: /usr/share/doc/cos-upgrade/html/index.html
Files: /usr/share/doc/cos-upgrade/html/*.html
